name: 1000 words
favicon: null
layout_spectrum: 0.2770894393324852
typography_spectrum: 0.833360651275143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5347459111362696
  lightness: 0.6683336354326457
  saturation: 0.9513492928817868
  rhythmicContrast: 0.8390446046832949
purpose: []
