name: 1000 words
favicon: null
layout_spectrum: 0.2770894393324852
typography_spectrum: 0.16174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f4d89'
    - '#dad8e3'
    - '#8599b1'
    - '#000000'
    - '#102b22'
  brandStrength: 0.5
  lightness: 0.6683336354326457
  saturation: 0.5
  rhythmicContrast: 0.8390446046832949
purpose: []
